### ISSUE TITLE
Migrate to RFC 7591/7592 API

### ISSUE THREAD

**Issue by jbasney** [cilogon/Oa4mpClient#1]
Now that https://github.com/ncsa/oa4mp supports the https://tools.ietf.org/html/rfc7591 and https://tools.ietf.org/html/rfc7592 standard OAuth APIs for client management, it'd be good for this plug-in to migrate from the old, proprietary OA4MP REST API to the RFC 7591/7592 API.

The old, proprietary OA4MP REST API is working fine and will continue to be supported, so the motivation for this enhancement is primarily that it's good to use standard APIs. Also, we're looking at using this plug-in with https://github.com/scitokens/scitokens-java and that project has a strong preference for following OAuth standards.

**Comment by skoranda** [comment]
Fixed in commit 6f4da39c33d7446d7f6a587b68afcf1042b82dde
